### ISSUE TITLE
Text and color issue

### ISSUE THREAD

**Issue by jojobozo** [itszechs/TorrentiumApp#2]
You added an extra s, it should be "1 month" and "2 months" and the navigation bar color isn't the same as the bottom bar too

![Screenshot_20220710-114725](https://user-images.githubusercontent.com/98482700/178139753-95a56feb-c7f9-4047-8192-e4ae07084b25.png)

**Comment by itszechs** [comment]
It's a known issue and has been fixed but yet to be released.
I plan on making the app open-source with next version so there is work to be done.
